// Auto generated: 2025-02-14 18:15:23
// do not modify this file
#pragma once

#include <cstdint>

namespace mllm::ir {

// NodeKind Enum Type for classof to use
// this enum is auto generated by rtti hierarchy generator.
// the enum class of LLVM style rtti.
//
// RTTI Kind (RK)
enum NodeKind : uint32_t {
  RK_None,
  RK_Op,
  RK_Op_LinalgIROp,
  RK_Op_LinalgIROp_CustomKernelOp,
  RK_Op_LinalgIROp_ElementwiseOp,
  RK_Op_LinalgIROp_ElementwiseOp_EAddOp,
  RK_Op_LinalgIROp_ElementwiseOp_ESubOp,
  RK_Op_LinalgIROp_ElementwiseOp_EMulOp,
  RK_Op_LinalgIROp_ElementwiseOp_EDivOp,
  RK_Op_LinalgIROp_ElementwiseOp_EBroadcastAddOp,
  RK_Op_LinalgIROp_ElementwiseOp_EBroadcastSubOp,
  RK_Op_LinalgIROp_ElementwiseOp_EBroadcastMulOp,
  RK_Op_LinalgIROp_ElementwiseOp_EBroadcastDivOp,
  RK_Op_LinalgIROp_ElementwiseOp_Last,
  RK_Op_LinalgIROp_MatMulOp,
  RK_Op_LinalgIROp_LinearOp,
  RK_Op_LinalgIROp_SDPAOp,
  RK_Op_LinalgIROp_RoPEOp,
  RK_Op_LinalgIROp_RoPE2dOp,
  RK_Op_LinalgIROp_Conv2dOp,
  RK_Op_LinalgIROp_Last,
  RK_Op_GraphIROp,
  RK_Op_GraphIROp_SubGraphOp,
  RK_Op_GraphIROp_CallGraphOp,
  RK_Op_GraphIROp_Last,
  RK_Op_TensorIROp,
  RK_Op_TensorIROp_AllocOp,
  RK_Op_TensorIROp_AllocGlobalOp,
  RK_Op_TensorIROp_FreeOp,
  RK_Op_TensorIROp_Last,
  RK_Op_BuiltinIROp,
  RK_Op_BuiltinIROp_ModuleOp,
  RK_Op_BuiltinIROp_Last,
  RK_Op_ControlFlowIROp,
  RK_Op_ControlFlowIROp_ReturnOp,
  RK_Op_ControlFlowIROp_Last,
  RK_Op_ProgramIROp,
  RK_Op_ProgramIROp_ObjectFragmentOp,
  RK_Op_ProgramIROp_DataFragmentOp,
  RK_Op_ProgramIROp_GlobalDataFragmentOp,
  RK_Op_ProgramIROp_InstructionOp,
  RK_Op_ProgramIROp_GlobalDataItemOp,
  RK_Op_ProgramIROp_DataItemOp,
  RK_Op_ProgramIROp_Last,
  RK_Op_Last,
  RK_Val,
  RK_Val_LinalgIRVal,
  RK_Val_GraphIRVal,
  RK_Val_TensorIRVal,
  RK_Val_TensorIRVal_TensorVal,
  RK_Val_TensorIRVal_Last,
  RK_Val_BuiltinIRVal,
  RK_Val_ControlFlowIRVal,
  RK_Val_ProgramIRVal,
  RK_Val_Last,
  RK_Attr,
  RK_Attr_LinalgIRAttr,
  RK_Attr_GraphIRAttr,
  RK_Attr_TensorIRAttr,
  RK_Attr_BuiltinIRAttr,
  RK_Attr_BuiltinIRAttr_IntAttr,
  RK_Attr_BuiltinIRAttr_FPAttr,
  RK_Attr_BuiltinIRAttr_StrAttr,
  RK_Attr_BuiltinIRAttr_SymbolAttr,
  RK_Attr_BuiltinIRAttr_Last,
  RK_Attr_ControlFlowIRAttr,
  RK_Attr_ProgramIRAttr,
  RK_Attr_Last,

};

class Node;
template<typename T>
struct NodeRTTIClassOfImpl {
  static inline bool classof(Node* v) { return false; }
};
}  // namespace mllm::ir
