// This file is generated by gen_opencl_kernel_cpp_wrap.py
// data     :Mon May 19 10:43:03 2025
//
// DO NOT MODIFY THIS FILE.
#pragma once

#include "mllm/Backends/OpenCL/Kernels/ElewiseAddFp16Buffer.hpp"
#include "mllm/Backends/OpenCL/Kernels/ElewiseAddFp16Image.hpp"
