// This file is generated by gen_opencl_kernel_cpp_warp.py
// data     :Sun May 18 11:15:36 2025
//
// DO NOT MODIFY THIS FILE.
#pragma once

#include "mllm/Backends/OpenCL/Kernels/ElewiseAddFp16Buffer.hpp"
#include "mllm/Backends/OpenCL/Kernels/ElewiseAddFp16Image.hpp"
